const VALIDATION_ERROR = 422;
const PERMISSION_DENIED = 400;
const UNAUTHORIZED = 401;
const NOT_FOUND = 404;
const ALREADY_EXIST = 422;
const INTERNAL_SERVER_ERROR = 500;

// Validation Error
const EMAIL_IS_NOT_VALID = 1000;
const PASSWORD_IS_NOT_VALID = 1005;